# Build
FROM node:20-alpine AS build
WORKDIR /app

# 👇 Recibir variables del entorno
ARG VITE_ENVIRONMENT
ARG VITE_API_URL

# 👇 Convertirlas en variables del sistema
ENV VITE_ENVIRONMENT=development
ENV VITE_API_URL=https://api.inmero.co/sigcon/dev

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build

# Serve
FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
