services:
  backend:
    build: .
    container_name: backend-api
    ports:
      - "${backend_port_api}:${backend_port_api}"
    depends_on:
    - ${backend_host}
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${backend_host}:${backend_port}/${backend_database}
      SPRING_DATASOURCE_USERNAME: ${backend_user}
      SPRING_DATASOURCE_PASSWORD: ${backend_password}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-PRODUCTION}
      FRONTEND_URL: ${FRONTEND_URL:-https://inmero.co/sigcon}
    deploy:
      resources:
        limits:
          memory: 384M

  db:
    image: postgres:15
    container_name: backend-db
    restart: always
    environment:
      POSTGRES_DB: ${backend_database}
      POSTGRES_USER: ${backend_user}
      POSTGRES_PASSWORD: ${backend_password}
    ports:
      - "${backend_port}:${backend_port}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

#  pgadmin:
#    image: dpage/pgadmin4
#    container_name: backend-pgadmin
#    ports:
#    - "5050:80"
#    environment:
#    PGADMIN_DEFAULT_EMAIL: admin@admin.com
#    PGADMIN_DEFAULT_PASSWORD: admin
#    depends_on:
#    - db

  adminer:
    image: adminer
    container_name: backend-adminer
    restart: always
    ports:
      - "${backend_port_adminer}:${backend_port_api}"
    depends_on:
      - ${backend_host}

volumes:
  postgres_data:
